---
- name: Reload postgresql
  service: name=postgresql state=reloaded

- name: Restart postgresql
  service: name=postgresql state=restarted

- name: Reload iptables rules
  service: name=iptables-persistent state=reloaded
